marin-community/marin

- infra/marin-eu-west4-vllm.yaml
- infra/marin-us-central2-vllm.yaml
- infra/marin-us-east1-d-vllm.yaml
- infra/marin-us-east5-b-vllm.yaml
- infra/marin-vllm-template.yaml
Some rough benchmarking:
Model | GCSFuse Mount with Cache Directory - grpc | GCSFuse Mount without cache directory
-- | -- | --
Llama-8b | 1 minute 37 seconds | 1 hour
Llama-70b | 14 minutes | N/A
> Fixes for GCSFuse to use local file cache

- marin/execution/executor.py
- tests/test_executor.py
This allows to construct more complete experiment json's in the common case that we don't let a certain dependency finish.
We need this to get the Marin 8B run fully documented in an experiment.json
> Add pseudo-dependencies / skip_parents to the Executor

- data_browser/src/ExperimentPage.js
Problem was that [this experiment JSON](https://marin-data-browser-748532799086.us-central1.run.app/experiment?path=gs%3A%2F%2Fmarin-us-east1%2Fexperiments%2Fexp963_cascade_finemath-fa55e6.json) was not loading.
One of the values was an array, which couldn't be rendered by React directly.  So it just has to be quoted.
> make data browser render experiment JSONs with array values

- data_browser/conf/docker.conf
- data_browser/conf/gcp.conf
- data_browser/conf/local.conf
- data_browser/server.py
- data_browser/src/ExperimentPage.js
- data_browser/src/utils.js
1. Prevent people from downloading files that are too big (limit to 10MB)
2. Prevent people from reading past the first 100 lines of a jsonl/parquet file
3. Hack to make the URL show up properly as marin.community/...
4. Show initialize_from properly for SFT models
> pre-release fixes to data browser

- experiments/exp163_bert.py
- pyproject.toml
> BERT vs Fasttext

- experiments/tootsie/exp600_tootsie.py
To highlight the full life cycle of Marin, adds evals directly into Exp600 so that the single file would reproduce Marin-8B-Base and then evaluate it.
> Add Evals to 600

- marin/processing/tokenize/tokenize.py
- tests/processing/tokenize/test_tokenize.py
Adds validation to `TokenizeConfig` to prevent accidental inclusion of
test or validation datasets in training data.
The validation checks if any of the `train_paths` in `TokenizeConfig`
contain the whole word "test" (e.g., "/test/") or "validation"
(e.g., "/validation/"). If such a pattern is found, a `ValueError`
is raised.
Unit tests have been added to `tests/processing/tokenize/test_tokenize.py`
to cover various scenarios, ensuring the validation works as expected and
does not incorrectly flag valid URLs.
> feat: Validate training URLs for forbidden patterns

- experiments/tutorials/hello_world.py
Fixed experiments/tutorials/hello_world.py which was not working on GCP due to the use of open instead of fsspec.open to read from a GCS bucket.
> modified hello_word for gcs

- marin/execution/executor.py
we should write the infos before the experiment steps are launched in case something goes wrong.
> write_infos before steps are launched (for crashes, etc)

- pyproject.toml
**Describe the bug**
Running `pre-commit run --all-files` passes on local but fails on Github CI.
Running `uv run pre-commit run --all-files` results in the same issue.
**Additional context**
When the command is run on local, ruff seems to sort the imports alphabetically. Github CI seem to be enforcing another behavior. While I have verified that the local version of ruff is the same, this behavior still occurs. We ignore "I001" to make local ruff compatible with the Github CI version
> Change linter config for backward compatability

- src/marin/resources.py
Addresses #470
This enables Marin to use Levanter's variable multislice functionality (https://github.com/stanford-crfm/levanter/pull/1126) by setting `slice_count` to a list of allowed sizes. Levanter will pick an allowed size based on how many slices are actually available.
> Allow slice_count in TPUPodConfig to be a list of allowed counts

- docs/explanations/evaluation.md
- docs/explanations/executor.md
- docs/explanations/speedrun-flops-accounting.md
- docs/reports/markdownified-datasets.md
- docs/tutorials/submitting-speedrun.md
Some doc links were broken in [the move to the `/src/` layout](https://github.com/marin-community/marin/pull/1453). This updates all the `main/blob/marin/*` links in `docs/`.
> Update docs links to use src directory

- pyproject.toml
- src/marin/evaluation/evaluators/levanter_tpu_evaluator.py
Bumping levanter fixes the issue of the `ImportError` of `levanter.layers`. Bumping the lm-eval will allow us to run the `mmlu_sl` and `mmlu_sl_verb` tasks.
> Bump levanter and lm-eval versions

- pyproject.toml
- src/marin/core/runtime.py
- src/marin/execution/executor.py
- src/marin/markdown/markdown.py
- src/marin/processing/classification/dedupe.py
- tests/conftest.py
- tests/deduplication/test_dedupe.py
- tests/test_classification_inference_empty_glob.py
- tests/test_dry_run.py
- tests/test_executor.py
- tests/test_integration_test.py
- tests/test_utils.py
- uv.lock
Fix tests that were broken under xdist. uv run pytest -n 4 (or auto) now works as expected.
* Initialize a single Ray cluster across tests.
This re-uses the cluster across multiple testing jobs. There's a tradeoff that a previous module might leave Ray in a dirty state, but we should be able to rely on Ray's own isolation to deal with this.  When running with xdist, construct the cluster on worker 0 (or master if no parallelism is enabled). This reduces the risk of "multiple Ray clusters found" race condition when initializing the Ray client.
We need to disable 3 tests in xdist mode due to Ray weirdness.
* Switch runtime initialization for dedupe to use `uv` for initialization. i
This speeds up duplicate tests significantly and is ~50% faster to initialize. It's still slow.
* Fix …
> Test performance improvements.

- pyproject.toml
This gets us past one dependency issue.
We're still seeing duplicate ray version issues.
> Fix pyproject.toml using the forked dolma.

- src/marin/run/clean_ray_tpus.py
We could potentially run this in a "cron" job on Ray to cleanup periodically.
Example usage:
`uv run src/marin/run/clean_ray_tpus.py --pid=99999 --num-jobs=4 --tpu-type=v4-8`
> Add script to kill any processes lingering on a TPU node.

- docs/dev-guide/building-docs.md
- docs/dev-guide/contributing.md
- docs/recipes/add_dataset.md
- docs/tutorials/co-develop.md
- docs/tutorials/installation.md
- docs/tutorials/local-gpu.md
- docs/tutorials/tpu-cluster-setup.md
- pyproject.toml
Update installation docs to use uv sync first and then pip install -e, and removed a build requirement for sentence piece that failed when I spun up new clusters. The install doc workflow should be working and verified for MacOS now
> update docs to use uv sync, ensured reproducibility on MacOS

- src/marin/run/ray_run.py
Exclude the git pack files since these files take a lot of space and can push us over the 100MB ray file limit when uploading to the cluster.
> Exclude pack files because git takes a lot of space

- experiments/exp1247_rl_async.py
- src/marin/post_training/train_worker.py
- src/marin/post_training/weight_transfer/__init__.py
- src/marin/post_training/weight_transfer/arrow_flight.py
- src/marin/post_training/weight_transfer/base.py
- tests/post_training/config_helpers.py
- tests/post_training/test_weight_transfer.py
This adds the "Arrow Flight": https://arrow.apache.org/docs/format/Flight.html backend for weight transfer.
It seems to work pretty well? It builds on gRPC serving & serialization, and has all of the nice features like timeouts & cancellation we might want.
> The client may be able to cancel the returned FlightInfo by CancelFlightInfo action. The client need to use DoAction with CancelFlightInfo action type to cancel the FlightInfo.
> A server should not respond until the result would be different from last time. That way, the client can “long poll” for updates without constantly making requests. Clients can set a short timeout to avoid blocking calls if desired.
> Add Arrow Flight backend for weight transfer

- scripts/ray/cluster.py
- src/marin/rl/curriculum.py
- src/marin/rl/rollout_worker.py
- tests/rl/test_curriculum.py
We were inadvertently using jax.random.choice for sampling, which by default attempts to grab access to the TPU device. As the curriculum actor doesn't declare a TPU resource, this results in a conflict with whatever other task is on the machine.
> Only accept scalars & numpy values to the curriculum actor

- experiments/exp1247_rl_async.py
- src/marin/rl/curriculum.py
- src/marin/rl/rl_losses.py
* Set an explicit rollout delay to avoid training on old batches.
This should be captured implicitly by the `alpha` parameter on the replay buffer, but that only takes into account when the training worker ingested the data, not the training weight it came from. Dropping older buffers is a sanity check against rollout workers which have fallen behind for some reason.
The weight used to tag a batch is the weight the worker has loaded when the batch _finishes_, so we shouldn't accidentally throw away any batches that simply took a while to produce.
* Up the default number of generations to 16 to get a better RLOO advantage sample.
* Use the mean over abs(rewards) when computing plateaus.
We end up with plateaus which look like:
I'm not totally happy with this but it's better than before, …
> Tweaks to the RL experiment template and plateau detection

- docs/design/rl-rollout-metadata-migration.md
- experiments/exp1247_rl_async.py
- src/marin/rl/environments/base.py
- src/marin/rl/environments/mock_env.py
- src/marin/rl/replay_buffer.py
- src/marin/rl/rl_job.py
- src/marin/rl/rl_losses.py
- src/marin/rl/rollout_worker.py
- src/marin/rl/train_worker.py
- src/marin/rl/types.py
- src/marin/rl/weight_transfer/base.py
- tests/rl/environments/test_mock_env.py
- tests/rl/integration/config.py
- tests/rl/integration/tasks.py
- tests/rl/integration/test_cats_integration.py
- tests/rl/integration/test_sequential_digits_integration.py
- tests/rl/test_replay_buffer.py
- tests/rl/test_rollout_storage.py
This moves rollout metadata onto the individual rollouts, which will eventually let us track rollout weight_ids separately from their group or batch. (For now we tag rollouts with the weight_id after the batch is complete).
This reduces the need to track the batch metadata around as we move rollouts as well.
We additionally add a max_timestamp_delay field to the replay buffer. This discards rollouts which are read from the rollout storage that happen to have an old timestamp even if they have a valid step id. This guards against restoring from a checkpoint and pulling stale rollouts from the storage.
We also move the inference context out of the rollout worker, as its only dependency is on a tokenizer and an API server address, and it's more associated with the environments.
> Refactor rollout & inference context code.

- src/marin/rl/curriculum.py
- src/marin/rl/robust_actor.py
- src/marin/rl/rollout_worker.py
- src/marin/rl/weight_transfer/arrow_flight.py
- src/marin/rl/weight_transfer/base.py
- src/marin/rl/weight_transfer/jax.py
- tests/rl/integration/config.py
Ray will retry actor tasks, but doesn't seem to handle actor failures unless some task explicitly attempts to recreate the actor. This introduce a simple wrapper class which catches the ActorDied exception and attempts to recreate the actor in that case.
Fixes #1719.
> Create RobustActor class for handling actor failure.
