.readthedocs.yaml
[Please include a summary of the changes and the related issue.]
=> Adding rtd changes

docs/css/custom.css, docs/tutorials/first-experiment.md, docs/tutorials/getting-started.md, mkdocs.yml, pyproject.toml
Closes #1216 
Closes #1217
Closes #1219 
Closes #1220 
Tabs and font changes:
=> Docs Revamp

infra/marin-big-run.yaml, infra/marin-us-central1.yaml, infra/update-cluster-configs.py
[Please include a summary of the changes and the related issue.]
=> bump docker in big-run, bigger workers in central1

docs/tutorials/data-browser.md, docs/tutorials/first-experiment.md, docs/tutorials/submitting-speedrun.md
* Adding import to the snippets for reduced friction
* Adding GPU snippets for speedrun
* npm i command addition in databrowser docs
=> Docs review and fixes

docs/references/default-steps.md, marin/export/__init__.py, marin/export/hf_upload.py, marin/utilities/fn_utils.py
Adds a step to upload to HF. This step is smart enough to handle GCS paths. I haven't stress tested it but it basically works.
=> Step for upload_to_hf

data_browser/package-lock.json, data_browser/package.json
i think this fixes most of the remaining problems?
=> ran npm audit

experiments/exp575_wikipedia_markdownify.py, experiments/exp579_ar5iv_markdownify.py, experiments/exp822_stackexchange_markdownify.py, experiments/exp934_hq_vs_pt.py, tests/test_slice_cache.py, tests/test_utils.py
Removes a lot of hard-coded paths used in Marin 8B
=> remove a lot of hardcoding of paths

data_browser/src/ExperimentPage.js
Allow MoE parameters to show up in the data browser:
=> add moe parameters to data browser

marin/speedrun/create_leaderboard.py
Reorder fields to avoid GH CI error about args order...
=> Update leaderboard script

docs/system-prompts/05-18-2025.md
Misc. From Discord!
I plugged in the marin.community homepage into Claude and asked it to generate a system prompt. I think this is as reasonable as anything.
=> Document System Prompt

docs/tutorials/installation.md
=> Patch link in docs

experiments/tootsie/exp1295_32b.py, experiments/tootsie/exp1380_muon32b.py, marin/evaluation/visualize.py, marin/training/training.py
=> Run Muon for a bit on the 32b, see how it goes

marin/execution/executor.py
Resolve the issue of heavy load causing failed jobs due to the below issue.
```
Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/util/state/api.py", line 737, in get_task
return StateApiClient(address=address).get(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/util/state/api.py", line 305, in get
list_api_response = self._make_http_get_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ray/anaconda3/lib/python3.11/site-packages/ray/util/state/api.py", line 228, in _make_http_get_request
raise RayStateApiException(
ray.util.state.exception.RayStateApiException: API server …
```
=> Treat Ray Failure as Unknown State

experiments/exp1330_scaling_code.py
Follows @nikil-ravi's ladder suite setup to train a set of scaling ladder models for programming languages.
Fixes #1330
=> Scaling Suite for Code

marin/markdown/markdown.py, pyproject.toml
[Please include a summary of the changes and the related issue.]
=> another attempt at fixing CI?

experiments/speedrun/adamc_llama_scaling/130m/speedrun_results.json, experiments/speedrun/adamc_llama_scaling/1_2b/speedrun_results.json, experiments/speedrun/adamc_llama_scaling/300m/speedrun_results.json, experiments/speedrun/adamc_llama_scaling/520m/speedrun_results.json, experiments/speedrun/adamc_llama_scaling/adamc_sweep.py, experiments/speedrun/adamw_llama_scaling/130m/speedrun_results.json, experiments/speedrun/adamw_llama_scaling/1_2b/speedrun_results.json, experiments/speedrun/adamw_llama_scaling/300m/speedrun_results.json, experiments/speedrun/adamw_llama_scaling/520m/speedrun_results.json, experiments/speedrun/adamw_llama_scaling/adamw_sweep.py, experiments/speedrun/muon_llama_scaling/130m/speedrun_results.json, experiments/speedrun/muon_llama_scaling/1_2b/speedrun_results.json, experiments/speedrun/muon_llama_scaling/300m/speedrun_results.json, experiments/speedrun/muon_llama_scaling/520m/speedrun_results.json, experiments/speedrun/muon_llama_scaling/muon_sweep.py, marin/speedrun/create_leaderboard.py
Runs a chinchilla optimal suite of scaling speedruns based on @WhenWen's Muon configs.
=> Muon Speedrun Scaling

experiments/datashop/default_configs.py, experiments/datashop/defaults.py, experiments/evals/evals.py, experiments/evals/task_configs.py, experiments/exp1361_datashop_medical.py, marin/evaluation/evaluators/lm_evaluation_harness_evaluator.py, marin/evaluation/run.py, marin/generation/inference.py, marin/generation/pipeline.py, marin/validation/get_env.py, tests/ray-data/test_batch_llm_inference.py, tests/tpu/test_xla_initialization.py
#1361 
Small fixes for the evaluation pipeline + datashop medical experiment.
Experiment results: https://marin.community/data-browser/experiment/?path=gs%3A//marin-us-east1/experiments/exp1361_datashop_medical-9c0f63.json
Benchmark | Tootsie from 660k checkpoint | Medical-tootsie annealed from 660k checkpoint | Llama 3.1-8B Instruct | Llama-3.1-8B-Base
-- | -- | -- | -- | --
PubmedQA | 0.754 | 0.758 | 0.754 | 0.77
MedMCQA | 0.386 | 0.452 | 0.589 | 0.584
HeadQA | 0.359 | 0.391 | 0.419 | 0.406
We see around 7 point increase in MedMCQA and 4 points in HeadQA
=> Datashop medical experiment

marin/post_training/llama3.py, marin/rl/__init__.py, marin/rl/config.py, marin/rl/env.py, marin/rl/envs/hello.py, marin/rl/envs/math_env.py, marin/rl/envs/openai_echo.py, marin/rl/parquet_store.py, marin/rl/types.py, pyproject.toml, scripts/install_all_pip_dep.py, tests/rl/test_math_env.py, tests/rl/test_openai_env.py, tests/rl/test_parquet_store.py
Part of #1416 
Let o3 take the wheel a bit. but it seems pretty good
=> RL v2 sketch: env and configs

experiments/multilingual-fineweb2-hq/download_and_tokenize_fineweb2_hq.py, experiments/multilingual_fineweb2_hq/constants.py, experiments/multilingual_fineweb2_hq/download_and_tokenize_fineweb2_hq.py
Has to do with https://github.com/marin-community/marin/issues/1457 
This adds tokenization for FineWeb2-HQ, in preparation for continued training of the 8B model.
=> Add tokenization for fineweb2-hq for multilingual experiments

pyproject.toml
- Add swebench dependency (excluding macOS to avoid compatibility issues)
- Update dolma git source to marin-community fork
=> Update dependencies for RL experiments

pyproject.toml
Updated levanter dependency to version 1.2.dev1535.
=> Update levanter dependency version

.github/workflows/update-leaderboard.yml
Directory restructure broke this workflow!
=> Fix Speedrun Update Script

AUTHORS.md
[Please include a summary of the changes and the related issue.]
=> Add Open Athena AI Foundation, Inc. as an author

scripts/ray/cluster.py, src/marin/cluster/gcp.py, src/marin/cluster/ray.py
=> Terminate TPUs explicitly when stopping or restarting clusters.

src/marin/post_training/replay_buffer.py, src/marin/post_training/rollout_storage.py, src/marin/post_training/train_worker.py, tests/post_training/test_replay_buffer.py
This adjusts how many times an example may be selected before it is retired. If this is set to a low value, then the training system may stall waiting for more rollouts.
The previous behavior allowed unlimited samples which could cause the trainer to go wildly off of the desired policy with a small replay buffer or if rollout workers fell behind for any reason.
=> Add a `max_resamples` parameter to the replay buffer.

experiments/evals/evals.py, experiments/evals/resource_configs.py, experiments/tootsie/exp1529_32b_bison_cooldown.py, src/marin/evaluation/evaluators/evaluator.py, src/marin/evaluation/evaluators/levanter_lm_eval_evaluator.py, src/marin/evaluation/evaluators/levanter_tpu_evaluator.py, src/marin/evaluation/run.py, src/marin/evaluation/utils.py
=> 32B Pretraining Cooldown (Codename: Bison)

experiments/exp1247_rl_async.py, pyproject.toml, src/marin/rl/environments/base.py, src/marin/rl/environments/mock_env.py, src/marin/rl/environments/prime_intellect_env.py, src/marin/rl/rollout_worker.py, src/marin/rl/scripts/export_env_prompts.py, src/marin/rl/scripts/test_llama_small.py, src/marin/rl/weight_transfer/arrow_flight.py, tests/rl/config_helpers.py, tests/rl/environments/test_load_environment.py, tests/rl/environments/test_prime_intellect_env.py, uv.lock
This changes environment loading to operate off a KV dictionary instead of manual string parsing. This is still sub-optimal: I'd prefer environments to take a typed configuration object or something similar, but makes it easier to pass through more complex environment configuration in the meantime.
=> Adjust environment initialization for the RL framework.

AGENTS.md
Happy to put this in recipes instead, I figured for coding tasks we might want some common rules however.
=> Add some more coding guidelines for agents.

src/marin/rl/rollout_worker.py
We currently don't have multi-slice rollout workers in any case - and we may not want them to share a seed in that case - but we can decide when that time comes.
=> Seed rollout slices independently (but identically across workers in a slice)

scripts/ray/cluster.py
=> Improve the message when we fail to save jobs for a cluster.

data_browser/conf/gcp.conf
=> Add central1 to data browswer
